# Generated by Django 5.2.4 on 2025-09-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "church_finances",
            "0003_churchmember_address_churchmember_baptism_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="churchmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Church Admin"),
                    ("treasurer", "Treasurer"),
                    ("pastor", "Pastor"),
                    ("assistant_pastor", "Assistant Pastor"),
                    ("deacon", "Deacon"),
                ],
                default="member",
                max_length=20,
            ),
        ),
    ]
