# Generated by Django 5.2.4 on 2025-09-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("church_finances", "0004_alter_churchmember_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="church",
            name="subscription_status",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.AddField(
            model_name="church",
            name="subscription_type",
            field=models.CharField(
                choices=[("standard", "Standard"), ("premium", "Premium")],
                default="standard",
                max_length=20,
            ),
        ),
    ]
