# Generated by Django 5.2.4 on 2025-09-08 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("church_finances", "0005_church_subscription_status_church_subscription_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayPalWebhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=100, unique=True)),
                ("event_type", models.CharField(max_length=100)),
                ("resource_type", models.CharField(max_length=100)),
                ("subscription_id", models.CharField(blank=True, max_length=100)),
                ("data", models.JSONField()),
                ("processed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="church",
            name="paypal_subscription_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="church",
            name="subscription_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="church",
            name="subscription_start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="church",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("cancelled", "Cancelled"),
                    ("suspended", "Suspended"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PayPalSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subscription_id", models.CharField(max_length=100, unique=True)),
                ("plan_id", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPROVAL_PENDING", "Approval Pending"),
                            ("APPROVED", "Approved"),
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        max_length=20,
                    ),
                ),
                ("payer_id", models.CharField(blank=True, max_length=100)),
                ("payer_email", models.EmailField(blank=True, max_length=254)),
                ("create_time", models.DateTimeField()),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("next_billing_time", models.DateTimeField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "church",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paypal_subscription",
                        to="church_finances.church",
                    ),
                ),
            ],
        ),
    ]
