# Generated by Django 5.2.4 on 2025-09-26 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church_finances', '0006_church_payment_fields'),
        ('church_finances', '0006_paypalwebhook_church_paypal_subscription_id_and_more'),
    ]

    operations = [
    ]
