# Generated by Django 5.2.4 on 2025-10-03 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_finances', '0007_merge_20250926_2118'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('grade_level', models.CharField(blank=True, choices=[('nursery', 'Nursery (0-2 years)'), ('toddler', 'Toddler (2-3 years)'), ('preschool', 'Preschool (3-5 years)'), ('kindergarten', 'Kindergarten'), ('1st_grade', '1st Grade'), ('2nd_grade', '2nd Grade'), ('3rd_grade', '3rd Grade'), ('4th_grade', '4th Grade'), ('5th_grade', '5th Grade'), ('6th_grade', '6th Grade'), ('7th_grade', '7th Grade'), ('8th_grade', '8th Grade'), ('9th_grade', '9th Grade'), ('10th_grade', '10th Grade'), ('11th_grade', '11th Grade'), ('12th_grade', '12th Grade'), ('graduated', 'Graduated')], max_length=20)),
                ('sunday_school_class', models.CharField(blank=True, choices=[('nursery', 'Nursery'), ('toddlers', 'Toddlers'), ('preschool', 'Preschool'), ('elementary', 'Elementary'), ('middle_school', 'Middle School'), ('high_school', 'High School'), ('youth', 'Youth Group')], max_length=20)),
                ('baptism_date', models.DateField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_relationship', models.CharField(blank=True, help_text='e.g., Grandmother, Uncle, Family Friend', max_length=50)),
                ('allergies', models.TextField(blank=True, help_text='List any known allergies or medical conditions')),
                ('medications', models.TextField(blank=True, help_text='List any regular medications')),
                ('medical_notes', models.TextField(blank=True, help_text='Any other important medical information')),
                ('address', models.TextField(blank=True, help_text="If different from parents' address")),
                ('phone_number', models.CharField(blank=True, help_text='If child has own phone', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Is the child currently attending?')),
                ('notes', models.TextField(blank=True, help_text='General notes about the child')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='church_finances.church')),
                ('parents', models.ManyToManyField(blank=True, help_text='Select the parent(s) or guardian(s) from church members', related_name='children', to='church_finances.churchmember')),
            ],
            options={
                'verbose_name': 'Child',
                'verbose_name_plural': 'Children',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ChildAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('activity_type', models.CharField(choices=[('sunday_service', 'Sunday Service'), ('sunday_school', 'Sunday School'), ('vbs', 'Vacation Bible School'), ('youth_group', 'Youth Group'), ('special_event', 'Special Event'), ('camp', 'Church Camp'), ('other', 'Other Activity')], max_length=20)),
                ('activity_name', models.CharField(blank=True, help_text='Name of specific activity or event', max_length=100)),
                ('present', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='church_finances.child')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church_finances.church')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('child', 'date', 'activity_type')},
            },
        ),
    ]
