# Generated by Django 5.2.4 on 2025-10-03 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_finances', '0008_add_children_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BabyChristening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby_first_name', models.CharField(help_text="Baby's first name", max_length=100)),
                ('baby_last_name', models.CharField(help_text="Baby's last name", max_length=100)),
                ('baby_date_of_birth', models.DateField(blank=True, help_text="Baby's date of birth", null=True)),
                ('christening_date', models.DateField(help_text='Date of christening ceremony')),
                ('christening_time', models.TimeField(blank=True, help_text='Time of ceremony', null=True)),
                ('pastor', models.CharField(help_text='Pastor who performed the christening', max_length=200)),
                ('ceremony_notes', models.TextField(blank=True, help_text='Special notes about the ceremony')),
                ('father_name', models.CharField(blank=True, help_text="Father's full name", max_length=200)),
                ('mother_name', models.CharField(blank=True, help_text="Mother's full name", max_length=200)),
                ('godfather_name', models.CharField(blank=True, help_text="Godfather's full name", max_length=200)),
                ('godmother_name', models.CharField(blank=True, help_text="Godmother's full name", max_length=200)),
                ('other_godparents', models.TextField(blank=True, help_text='Additional godparents')),
                ('contact_address', models.TextField(blank=True, help_text='Family contact address')),
                ('contact_phone', models.CharField(blank=True, help_text='Primary contact phone', max_length=20)),
                ('contact_email', models.EmailField(blank=True, help_text='Contact email address', max_length=254)),
                ('certificate_number', models.CharField(blank=True, help_text='Christening certificate number', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Active record')),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='christened_babies', to='church_finances.church')),
                ('parent_members', models.ManyToManyField(blank=True, help_text='Parents who are church members', related_name='christened_babies', to='church_finances.churchmember')),
                ('recorded_by', models.ForeignKey(help_text='Person who recorded this christening', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-christening_date'],
                'unique_together': {('baby_first_name', 'baby_last_name', 'christening_date', 'church')},
            },
        ),
    ]
