# Generated by Django 4.2.7 on 2025-10-18 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church_finances', '0006_remove_premium_subscription'),
        ('church_finances', '0009_add_baby_christening_model'),
    ]

    operations = [
    ]
