# Generated by Django 4.2.7 on 2025-10-18 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('church_finances', '0010_merge_20251018_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='registered_by',
            field=models.ForeignKey(blank=True, help_text='User who originally registered this church', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_churches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='church',
            name='subscription_type',
            field=models.CharField(choices=[('standard', 'Church Books')], default='standard', max_length=20),
        ),
    ]
