# Generated by Django 5.2.4 on 2025-10-23 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church_finances', '0007_migrate_address_data'),
        ('church_finances', '0011_add_registered_by_to_church'),
    ]

    operations = [
    ]
