# Generated by Django 5.2.4 on 2025-10-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_finances', '0012_merge_20251023_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babychristening',
            name='contact_address',
        ),
        migrations.RemoveField(
            model_name='child',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='child',
            name='medical_notes',
        ),
        migrations.RemoveField(
            model_name='child',
            name='medications',
        ),
        migrations.AddField(
            model_name='babychristening',
            name='contact_city',
            field=models.CharField(blank=True, help_text='City', max_length=100),
        ),
        migrations.AddField(
            model_name='babychristening',
            name='contact_country',
            field=models.CharField(blank=True, default='United States', help_text='Country', max_length=100),
        ),
        migrations.AddField(
            model_name='babychristening',
            name='contact_state',
            field=models.CharField(blank=True, help_text='State/Province', max_length=100),
        ),
        migrations.AddField(
            model_name='babychristening',
            name='contact_street_address',
            field=models.CharField(blank=True, help_text='Street address', max_length=255),
        ),
        migrations.AddField(
            model_name='babychristening',
            name='contact_zip_code',
            field=models.CharField(blank=True, help_text='ZIP/Postal code', max_length=20),
        ),
        migrations.AddField(
            model_name='child',
            name='city',
            field=models.CharField(blank=True, help_text='City', max_length=100),
        ),
        migrations.AddField(
            model_name='child',
            name='country',
            field=models.CharField(blank=True, default='United States', help_text='Country', max_length=100),
        ),
        migrations.AddField(
            model_name='child',
            name='state',
            field=models.CharField(blank=True, help_text='State/Province', max_length=100),
        ),
        migrations.AddField(
            model_name='child',
            name='street_address',
            field=models.CharField(blank=True, help_text='Street address', max_length=255),
        ),
        migrations.AddField(
            model_name='child',
            name='zip_code',
            field=models.CharField(blank=True, help_text='ZIP/Postal code', max_length=20),
        ),
        migrations.AlterField(
            model_name='child',
            name='address',
            field=models.TextField(blank=True, help_text="If different from parents' address (legacy field)"),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='role',
            field=models.CharField(choices=[('admin', 'Church Admin'), ('treasurer', 'Treasurer'), ('pastor', 'Pastor'), ('bishop', 'Bishop'), ('assistant_pastor', 'Assistant Pastor'), ('deacon', 'Deacon')], default='member', max_length=20),
        ),
    ]
