# Generated by Django 4.2.7 on 2025-12-08 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("church_finances", "0013_remove_babychristening_contact_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="church",
            name="is_trial_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether the church is currently in trial period",
            ),
        ),
        migrations.AddField(
            model_name="church",
            name="trial_end_date",
            field=models.DateTimeField(
                blank=True, help_text="Date when the 30-day trial expires", null=True
            ),
        ),
        migrations.AddField(
            model_name="church",
            name="trial_expired_notified",
            field=models.BooleanField(
                default=False,
                help_text="Whether user has been notified about trial expiration",
            ),
        ),
        migrations.AddField(
            model_name="church",
            name="trial_start_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Date when the 30-day trial started",
            ),
        ),
    ]
