# Generated by Django 4.2.7 on 2026-02-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "church_finances",
            "0014_church_is_trial_active_church_trial_end_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="church",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Upload your church logo (PNG or JPG recommended)",
                null=True,
                upload_to="church_logos/",
            ),
        ),
    ]
