# Generated by Django 4.2.7 on 2026-02-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("church_finances", "0015_church_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="church",
            name="logo_base64",
            field=models.TextField(
                blank=True,
                help_text="Base64-encoded logo for print reports (stored in DB, survives server restarts)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="church",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("paypal", "PayPal"),
                    ("offline", "Offline"),
                    ("bank_transfer", "Bank Transfer"),
                ],
                default="offline",
                max_length=20,
            ),
        ),
    ]
