# Generated by Django 5.2.4 on 2026-02-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("church_finances", "0016_add_logo_base64_to_church"),
    ]

    operations = [
        migrations.AlterField(
            model_name="church",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe"),
                    ("paypal", "PayPal"),
                    ("offline", "Offline"),
                    ("bank_transfer", "Bank Transfer"),
                ],
                default="offline",
                max_length=20,
            ),
        ),
    ]
