# Generated by Django 5.2.4 on 2026-03-30 16:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("church_finances", "0017_add_stripe_payment_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                (
                    "street_address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Street Address"
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                (
                    "zip_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="ZIP/Postal Code"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default="United States", max_length=100
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single", "Single"),
                            ("married", "Married"),
                            ("widowed", "Widowed"),
                            ("divorced", "Divorced"),
                        ],
                        max_length=20,
                    ),
                ),
                ("baptism_date", models.DateField(blank=True, null=True)),
                (
                    "membership_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="church_finances.church",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member",
                "verbose_name_plural": "Members",
                "ordering": ["last_name", "first_name"],
            },
        ),
        # Step 1: Create the Member model first.
        # ---------------------------------------------------------------
        # Step 2: Surgically clear all old ChurchMember-based data so the
        # subsequent AlterField operations can add new FK constraints to the
        # (empty) Member table without integrity errors.
        #
        # a) Drop FK constraint on contribution.member_id (name is dynamic),
        #    make column nullable, then NULL out all existing values.
        # b) Delete all rows in both M2M junction tables.
        migrations.RunSQL(
            sql="""
            DO $$
            DECLARE
                fk_name text;
            BEGIN
                SELECT tc.constraint_name INTO fk_name
                FROM information_schema.table_constraints tc
                JOIN information_schema.key_column_usage kcu
                    ON tc.constraint_name = kcu.constraint_name
                   AND tc.table_schema    = kcu.table_schema
                WHERE tc.table_schema  = 'public'
                  AND tc.table_name    = 'church_finances_contribution'
                  AND kcu.column_name  = 'member_id'
                  AND tc.constraint_type = 'FOREIGN KEY'
                LIMIT 1;

                IF fk_name IS NOT NULL THEN
                    EXECUTE 'ALTER TABLE church_finances_contribution DROP CONSTRAINT ' || quote_ident(fk_name);
                END IF;
            END
            $$;

            ALTER TABLE church_finances_contribution
                ALTER COLUMN member_id DROP NOT NULL;

            UPDATE church_finances_contribution SET member_id = NULL;

            DELETE FROM church_finances_babychristening_parent_members;
            DELETE FROM church_finances_child_parents;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Step 3: Now AlterField is safe — column is nullable, data is NULL,
        # M2M tables are empty — so adding new FK constraints will succeed.
        migrations.AlterField(
            model_name="contribution",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="church_finances.member",
            ),
        ),
        migrations.AlterField(
            model_name="babychristening",
            name="parent_members",
            field=models.ManyToManyField(
                blank=True,
                help_text="Parents who are church members",
                related_name="christened_babies",
                to="church_finances.member",
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="parents",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select the parent(s) or guardian(s) from church members",
                related_name="children",
                to="church_finances.member",
            ),
        ),
    ]
