# Generated by Django 5.2.4 on 2026-03-30 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "church_finances",
            "0018_member_alter_babychristening_parent_members_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="babychristening",
            table="cb_christenings",
        ),
        migrations.AlterModelTable(
            name="child",
            table="cb_children",
        ),
        migrations.AlterModelTable(
            name="childattendance",
            table="cb_child_attendance",
        ),
        migrations.AlterModelTable(
            name="church",
            table="cb_churches",
        ),
        migrations.AlterModelTable(
            name="churchmember",
            table="cb_staff_accounts",
        ),
        migrations.AlterModelTable(
            name="contribution",
            table="cb_contributions",
        ),
        migrations.AlterModelTable(
            name="member",
            table="cb_congregation_members",
        ),
        migrations.AlterModelTable(
            name="paypalsubscription",
            table="cb_paypal_subscriptions",
        ),
        migrations.AlterModelTable(
            name="paypalwebhook",
            table="cb_paypal_webhooks",
        ),
        migrations.AlterModelTable(
            name="transaction",
            table="cb_transactions",
        ),
    ]
