# Generated by Django 4.2.7 on 2026-03-31 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "church_finances",
            "0019_alter_babychristening_table_alter_child_table_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal label, e.g. 'Blue Christening'",
                        max_length=100,
                    ),
                ),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[
                            ("christening", "Christening / Baptism"),
                            ("membership", "Church Membership"),
                            ("baptism", "Adult Baptism"),
                            ("graduation", "Graduation"),
                            ("marriage", "Marriage Blessing"),
                            ("other", "Other"),
                        ],
                        default="christening",
                        max_length=30,
                    ),
                ),
                (
                    "title_text",
                    models.CharField(
                        default="Certificate of Christening",
                        help_text="Large heading on the certificate",
                        max_length=200,
                    ),
                ),
                (
                    "subtitle_text",
                    models.CharField(
                        blank=True,
                        help_text="Smaller subtitle below the title",
                        max_length=200,
                    ),
                ),
                (
                    "footer_text",
                    models.TextField(
                        blank=True,
                        help_text="Bible verse, motto, or signature line at the bottom",
                    ),
                ),
                (
                    "border_color",
                    models.CharField(
                        default="#1e3a5f",
                        help_text="Hex colour, e.g. #1e3a5f",
                        max_length=7,
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#1e3a5f",
                        help_text="Headings & accent colour",
                        max_length=7,
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#c9a84c",
                        help_text="Secondary accent (lines, dividers)",
                        max_length=7,
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#fdfaf4",
                        help_text="Certificate background colour",
                        max_length=7,
                    ),
                ),
                (
                    "border_style",
                    models.CharField(
                        choices=[
                            ("solid", "Solid"),
                            ("double", "Double"),
                            ("dashed", "Dashed"),
                            ("ornate", "Ornate (decorative corners)"),
                        ],
                        default="double",
                        max_length=20,
                    ),
                ),
                (
                    "border_width",
                    models.PositiveSmallIntegerField(
                        default=6, help_text="Border thickness in pixels"
                    ),
                ),
                (
                    "show_logo",
                    models.BooleanField(
                        default=True, help_text="Show church logo on certificate"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Use this template when printing this certificate type",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "church",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate_templates",
                        to="church_finances.church",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificate Template",
                "verbose_name_plural": "Certificate Templates",
                "db_table": "cb_certificate_templates",
                "ordering": ["certificate_type", "name"],
            },
        ),
    ]
