# Generated by Django 4.2.7 on 2026-03-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("church_finances", "0020_certificatetemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificatetemplate",
            name="background_color2",
            field=models.CharField(
                blank=True,
                default="#ffffff",
                help_text="Second colour for gradient background",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="certificatetemplate",
            name="background_style",
            field=models.CharField(
                choices=[("solid", "Solid Colour"), ("gradient", "Gradient")],
                default="solid",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="certificatetemplate",
            name="corner_style",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("filled", "Filled Triangle"),
                    ("slash", "Slash / Stripe"),
                ],
                default="none",
                help_text="Decorative corner accent style",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="certificatetemplate",
            name="gradient_direction",
            field=models.CharField(
                choices=[
                    ("to bottom right", "Diagonal ↘"),
                    ("to right", "Horizontal →"),
                    ("to bottom", "Vertical ↓"),
                    ("to top right", "Diagonal ↗"),
                    ("135deg", "Diagonal 135°"),
                ],
                default="to bottom right",
                max_length=30,
            ),
        ),
    ]
