# Generated by Django 4.2.7 on 2026-03-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("church_finances", "0021_add_gradient_corner_to_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificatetemplate",
            name="baptism_declaration",
            field=models.TextField(
                blank=True,
                default="was baptised in the name of the Father, the Son, and the Holy Spirit",
                help_text="The declaration sentence shown on the baptism certificate",
            ),
        ),
        migrations.AlterField(
            model_name="certificatetemplate",
            name="corner_style",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("filled", "Filled Triangles — All 4 Corners"),
                    ("slash", "Slash Stripe — All 4 Corners"),
                    ("diag2", "Diagonal Panels — Left & Right Sides"),
                    ("diag4", "Diagonal Panels — All 4 Corners"),
                    ("wave", "Wave Ribbon — Top-Right & Bottom-Left"),
                    ("tl_only", "Accent — Top-Left Corner Only"),
                    ("bracket", "Bracket Lines — Corner Borders"),
                    ("band_tb", "Full Band — Top & Bottom"),
                    ("double_tri", "Double Triangle — All 4 Corners"),
                    ("ribbon_side", "Ribbon Strip — Left Side Only"),
                ],
                default="none",
                help_text="Decorative corner accent style",
                max_length=20,
            ),
        ),
    ]
