# Generated by Django 4.2.7 on 2026-03-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("church_finances", "0022_add_baptism_declaration"),
    ]

    operations = [
        migrations.AddField(
            model_name="church",
            name="payment_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("paid", "Paid")],
                default="pending",
                help_text="Manual payment status set by admin",
                max_length=20,
            ),
        ),
    ]
