# Generated by Django 5.2.4 on 2026-04-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("church_finances", "0023_add_payment_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_verified", models.BooleanField(default=False)),
                ("attempts", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "cb_email_otps",
                "ordering": ["-created_at"],
            },
        ),
    ]
