# Generated by Django 5.2.4 on 2026-04-06 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("church_finances", "0024_add_email_otp"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    models.CharField(
                        choices=[
                            ("starter", "Starter"),
                            ("growth", "Growth"),
                            ("community", "Community"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "member_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Max active congregation members allowed. Null = custom tier (no hard cap).",
                        null=True,
                    ),
                ),
                (
                    "annual_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base annual price in USD.",
                        max_digits=8,
                    ),
                ),
                (
                    "is_custom",
                    models.BooleanField(
                        default=False,
                        help_text="If True the price is calculated from declared_member_count, not a fixed value.",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "cb_subscription_plans",
                "ordering": ["annual_price"],
            },
        ),
        migrations.AddField(
            model_name="church",
            name="declared_member_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Member count declared at signup — used to calculate custom tier price.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="church",
            name="subscription_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Actual annual subscription amount in USD (stored so custom price is preserved).",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="church",
            name="subscription_plan",
            field=models.ForeignKey(
                blank=True,
                help_text="The pricing tier this church is subscribed to. Null = legacy/no limit.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="churches",
                to="church_finances.subscriptionplan",
            ),
        ),
    ]
