# Generated by Django 5.2.4 on 2026-04-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("church_finances", "0025_subscription_plans_and_member_limits"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="contributor_name",
            field=models.CharField(
                blank=True,
                help_text="Name of contributor (for non-member offerings and other contributions)",
                max_length=100,
            ),
        ),
    ]
