# Generated by Django 5.2.4 on 2026-04-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("church_finances", "0026_add_contributor_name_to_contribution"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="from_contribution",
            field=models.BooleanField(
                default=False,
                help_text="True if this transaction was auto-created by the contribution sync.",
            ),
        ),
    ]
