# Generated by Django 4.2.24 on 2026-06-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_finances', '0027_add_from_contribution_to_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='guardian_names',
            field=models.TextField(blank=True, help_text='Parent or guardian names typed on the child form'),
        ),
    ]
