# Generated by Codex on 2026-06-09

from django.db import migrations, models


def _set_guardian_names_default(apps, schema_editor):
    schema_editor.execute("UPDATE cb_children SET guardian_names = '' WHERE guardian_names IS NULL;")
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("ALTER TABLE cb_children ALTER COLUMN guardian_names SET DEFAULT '';")


class Migration(migrations.Migration):

    dependencies = [
        ('church_finances', '0028_child_guardian_names'),
    ]

    operations = [
        migrations.RunPython(
            code=_set_guardian_names_default,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='child',
            name='guardian_names',
            field=models.TextField(blank=True, default='', help_text='Parent or guardian names typed on the child form'),
        ),
    ]
