# Generated by Codex on 2026-06-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_finances', '0028_child_guardian_names'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                UPDATE cb_children
                SET guardian_names = ''
                WHERE guardian_names IS NULL;

                ALTER TABLE cb_children
                ALTER COLUMN guardian_names SET DEFAULT '';
            """,
            reverse_sql="""
                ALTER TABLE cb_children
                ALTER COLUMN guardian_names DROP DEFAULT;
            """,
        ),
        migrations.AlterField(
            model_name='child',
            name='guardian_names',
            field=models.TextField(blank=True, default='', help_text='Parent or guardian names typed on the child form'),
        ),
    ]
