# Generated by Django 4.2.24 on 2026-06-19 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('church_finances', '0029_child_guardian_names_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cb_deleted_accounts',
            },
        ),
    ]
