# Generated by Django 4.2.24 on 2026-07-10 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church_finances', '0031_subscriptionplan_free_trial_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='donation_account_number',
            field=models.CharField(blank=True, db_index=True, help_text='Public account number used by donors to route online tithe/offering payments to this church.', max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ManagedPaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe Connect'), ('paypal', 'PayPal Multiparty'), ('wipay', 'WiPay Caribbean')], default='wipay', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('connected_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('wipay_account_id', models.CharField(blank=True, help_text="Church's WiPay Account ID", max_length=50, null=True)),
                ('wipay_country', models.CharField(blank=True, choices=[('TT', 'Trinidad & Tobago'), ('JM', 'Jamaica'), ('BB', 'Barbados'), ('GY', 'Guyana')], max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gateway', to='church_finances.church')),
            ],
            options={
                'verbose_name': 'Managed Payment Gateway',
                'verbose_name_plural': 'Managed Payment Gateways',
                'db_table': 'cb_managed_payment_gateways',
            },
        ),
    ]
