# Generated by Django 4.2.24 on 2026-07-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_finances', '0032_church_donation_account_number_managedpaymentgateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedpaymentgateway',
            name='paypal_tracking_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
