# Generated by Django 4.2.24 on 2026-07-10 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('church_finances', '0033_managedpaymentgateway_paypal_tracking_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('activity_type', models.CharField(choices=[('sunday_service', 'Sunday Service'), ('bible_study', 'Bible Study'), ('prayer_meeting', 'Prayer Meeting'), ('special_event', 'Special Event'), ('other', 'Other Activity')], max_length=20)),
                ('activity_name', models.CharField(blank=True, help_text='Name of specific activity or event', max_length=100)),
                ('present', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church_finances.church')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='church_finances.member')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cb_member_attendance',
                'ordering': ['-date'],
                'unique_together': {('member', 'date', 'activity_type')},
            },
        ),
    ]
