# Generated by Django 4.2.24 on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_finances', '0034_member_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='payment_method',
            field=models.CharField(
                choices=[
                    ('cash', 'Cash'),
                    ('check', 'Check'),
                    ('card', 'Credit/Debit Card'),
                    ('cbm_online', 'CBM Online'),
                    ('bank_transfer', 'Bank Transfer'),
                    ('mobile_money', 'Mobile Money'),
                ],
                max_length=20,
            ),
        ),
    ]
