# Generated by Django 4.2.24 on 2026-07-17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church_finances', '0035_alter_contribution_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='WiPayDonationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('contribution_type', models.CharField(choices=[('tithe', 'Tithe'), ('offering', 'Offering'), ('special_offering', 'Special Offering'), ('building_fund', 'Building Fund'), ('missions', 'Missions'), ('other', 'Other')], max_length=20)),
                ('donor_name', models.CharField(blank=True, max_length=100)),
                ('donor_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('verification_method', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wipay_donation_attempts', to='church_finances.church')),
                ('contribution', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wipay_attempt', to='church_finances.contribution')),
            ],
            options={
                'db_table': 'cb_wipay_donation_attempts',
                'ordering': ['-created_at'],
            },
        ),
    ]
