# Generated by Django 4.2.24 on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_finances', '0036_wipaydonationattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedpaymentgateway',
            name='wipay_account_type',
            field=models.CharField(choices=[('business', 'Verified Business Account'), ('personal', 'Personal Account')], default='business', max_length=20),
        ),
        migrations.AddField(
            model_name='managedpaymentgateway',
            name='wipay_api_key_encrypted',
            field=models.TextField(blank=True),
        ),
    ]
